<optgroup label="Aveiro">
    <option value=1>Castelo de Paiva</option>
    <option value=2>Espinho</option>
    <option value=3>Estarreja</option>
    <option value=4>Santa Maria da Feira</option>
    <option value=5>Ílhavo</option>
    <option value=6>Mealhada</option>
    <option value=7>Murtosa</option>
    <option value=8>Oliveira de Azeméis</option>
    <option value=9>Oliveira do Bairro</option>
    <option value=10>Ovar</option>
    <option value=11>São João da Madeira</option>
    <option value=12>Sever do Vouga</option>
    <option value=13>Vagos</option>
    <option value=14>Vale de Cambra</option>
    <option value=15>Águeda</option>
    <option value=16>Albergaria-a-Velha</option>
    <option value=17>Anadia</option>
    <option value=18>Arouca</option>
    <option value=19>Aveiro</option>
</optgroup>
<optgroup label="Beja">
    <option value=20>Castro Verde</option>
    <option value=21>Cuba</option>
    <option value=22>Ferreira do Alentejo</option>
    <option value=23>Mértola</option>
    <option value=24>Moura</option>
    <option value=25>Odemira</option>
    <option value=26>Ourique</option>
    <option value=27>Serpa</option>
    <option value=28>Vidigueira</option>
    <option value=29>Aljustrel</option>
    <option value=30>Almodôvar</option>
    <option value=31>Alvito</option>
    <option value=32>Barrancos</option>
    <option value=33>Beja</option>
</optgroup>
<optgroup label="Braga">
    <option value=34>Esposende</option>
    <option value=35>Fafe</option>
    <option value=36>Guimarães</option>
    <option value=37>Póvoa de Lanhoso</option>
    <option value=38>Terras de Bouro</option>
    <option value=39>Vieira do Minho</option>
    <option value=40>Vila Nova de Famalicão</option>
    <option value=41>Vila Verde</option>
    <option value=42>Vizela</option>
    <option value=43>Amares</option>
    <option value=44>Barcelos</option>
    <option value=45>Braga</option>
    <option value=46>Cabeceiras de Basto</option>
    <option value=47>Celorico de Basto</option>
</optgroup>
<optgroup label="Bragança">
    <option value=48>Miranda do Douro</option>
    <option value=49>Mirandela</option>
    <option value=50>Mogadouro</option>
    <option value=51>Torre de Moncorvo</option>
    <option value=52>Vila Flor</option>
    <option value=53>Vimioso</option>
    <option value=54>Vinhais</option>
    <option value=55>Alfândega da Fé</option>
    <option value=56>Bragança</option>
    <option value=57>Carrazeda de Ansiães</option>
    <option value=58>Freixo de Espada à Cinta</option>
    <option value=59>Macedo de Cavaleiros</option>
</optgroup>
<optgroup label="Castelo Branco">
    <option value=60>Oleiros</option>
    <option value=61>Penamacor</option>
    <option value=62>Proença-a-Nova</option>
    <option value=63>Sertã</option>
    <option value=64>Vila de Rei</option>
    <option value=65>Vila Velha de Ródão</option>
    <option value=66>Belmonte</option>
    <option value=67>Castelo Branco</option>
    <option value=68>Covilhã</option>
    <option value=69>Fundão</option>
    <option value=70>Idanha-a-Nova</option>
</optgroup>
<optgroup label="Coimbra">
    <option value=71>Góis</option>
    <option value=72>Lousã</option>
    <option value=73>Mira</option>
    <option value=74>Miranda do Corvo</option>
    <option value=75>Montemor-o-Velho</option>
    <option value=76>Oliveira do Hospital</option>
    <option value=77>Pampilhosa da Serra</option>
    <option value=78>Penacova</option>
    <option value=79>Penela</option>
    <option value=80>Soure</option>
    <option value=81>Tábua</option>
    <option value=82>Vila Nova de Poiares</option>
    <option value=83>Arganil</option>
    <option value=84>Cantanhede</option>
    <option value=85>Coimbra</option>
    <option value=86>Condeixa-a-Nova</option>
    <option value=87>Figueira da Foz</option>
</optgroup>
<optgroup label="Évora">
    <option value=88>Montemor-o-Novo</option>
    <option value=89>Mora</option>
    <option value=90>Mourão</option>
    <option value=91>Portel</option>
    <option value=92>Redondo</option>
    <option value=93>Reguengos de Monsaraz</option>
    <option value=94>Vendas Novas</option>
    <option value=95>Viana do Alentejo</option>
    <option value=96>Vila Viçosa</option>
    <option value=97>Alandroal</option>
    <option value=98>Arraiolos</option>
    <option value=99>Borba</option>
    <option value=100>Estremoz</option>
    <option value=101>Évora</option>
</optgroup>
<optgroup label="Faro">
    <option value=102>Lagoa (Algarve)</option>
    <option value=103>Lagos</option>
    <option value=104>Loulé</option>
    <option value=105>Monchique</option>
    <option value=106>Olhão</option>
    <option value=107>Portimão</option>
    <option value=108>São Brás de Alportel</option>
    <option value=109>Silves</option>
    <option value=110>Tavira</option>
    <option value=111>Vila do Bispo</option>
    <option value=112>Vila Real de Santo António</option>
    <option value=113>Albufeira</option>
    <option value=114>Alcoutim</option>
    <option value=115>Aljezur</option>
    <option value=116>Castro Marim</option>
    <option value=117>Faro</option>
</optgroup>
<optgroup label="Guarda">
    <option value=118>Gouveia</option>
    <option value=119>Guarda</option>
    <option value=120>Manteigas</option>
    <option value=121>Meda</option>
    <option value=122>Pinhel</option>
    <option value=123>Sabugal</option>
    <option value=124>Seia</option>
    <option value=125>Trancoso</option>
    <option value=126>Vila Nova de Foz Côa</option>
    <option value=127>Aguiar da Beira</option>
    <option value=128>Almeida</option>
    <option value=129>Celorico da Beira</option>
    <option value=130>Figueira de Castelo Rodrigo</option>
    <option value=131>Fornos de Algodres</option>
</optgroup>
<optgroup label="Leiria">
    <option value=132>Caldas da Rainha</option>
    <option value=133>Castanheira de Pêra</option>
    <option value=134>Figueiró dos Vinhos</option>
    <option value=135>Leiria</option>
    <option value=136>Marinha Grande</option>
    <option value=137>Nazaré</option>
    <option value=138>Óbidos</option>
    <option value=139>Pedrógão Grande</option>
    <option value=140>Peniche</option>
    <option value=141>Pombal</option>
    <option value=142>Porto de Mós</option>
    <option value=143>Alcobaça</option>
    <option value=144>Alvaiázere</option>
    <option value=145>Ansião</option>
    <option value=146>Batalha</option>
    <option value=147>Bombarral</option>
</optgroup>
<optgroup label="Lisboa">
    <option value=148>Lisboa</option>
    <option value=149>Loures</option>
    <option value=150>Lourinhã</option>
    <option value=151>Mafra</option>
    <option value=152>Oeiras</option>
    <option value=153>Sintra</option>
    <option value=154>Sobral de Monte Agraço</option>
    <option value=155>Torres Vedras</option>
    <option value=156>Vila Franca de Xira</option>
    <option value=157>Amadora</option>
    <option value=158>Odivelas</option>
    <option value=159>Alenquer</option>
    <option value=160>Arruda dos Vinhos</option>
    <option value=161>Azambuja</option>
    <option value=162>Cadaval</option>
    <option value=163>Cascais</option>
</optgroup>
<optgroup label="Portalegre">
    <option value=164>Crato</option>
    <option value=165>Elvas</option>
    <option value=166>Fronteira</option>
    <option value=167>Gavião</option>
    <option value=168>Marvão</option>
    <option value=169>Monforte</option>
    <option value=170>Nisa</option>
    <option value=171>Ponte de Sor</option>
    <option value=172>Portalegre</option>
    <option value=173>Sousel</option>
    <option value=174>Alter do Chão</option>
    <option value=175>Arronches</option>
    <option value=176>Avis</option>
    <option value=177>Campo Maior</option>
    <option value=178>Castelo de Vide</option>
</optgroup>
<optgroup label="Porto">
    <option value=179>Maia</option>
    <option value=180>Marco de Canaveses</option>
    <option value=181>Matosinhos</option>
    <option value=182>Paços de Ferreira</option>
    <option value=183>Paredes</option>
    <option value=184>Penafiel</option>
    <option value=185>Porto</option>
    <option value=186>Póvoa de Varzim</option>
    <option value=187>Santo Tirso</option>
    <option value=188>Valongo</option>
    <option value=189>Vila do Conde</option>
    <option value=190>Vila Nova de Gaia</option>
    <option value=191>Trofa</option>
    <option value=192>Amarante</option>
    <option value=193>Baião</option>
    <option value=194>Felgueiras</option>
    <option value=195>Gondomar</option>
    <option value=196>Lousada</option>
</optgroup>
<optgroup label="Santarém">
    <option value=197>Cartaxo</option>
    <option value=198>Chamusca</option>
    <option value=199>Constância</option>
    <option value=200>Coruche</option>
    <option value=201>Entroncamento</option>
    <option value=202>Ferreira do Zêzere</option>
    <option value=203>Golegã</option>
    <option value=204>Mação</option>
    <option value=205>Rio Maior</option>
    <option value=206>Salvaterra de Magos</option>
    <option value=207>Santarém</option>
    <option value=208>Sardoal</option>
    <option value=209>Tomar</option>
    <option value=210>Torres Novas</option>
    <option value=211>Vila Nova da Barquinha</option>
    <option value=212>Ourém</option>
    <option value=213>Abrantes</option>
    <option value=214>Alcanena</option>
    <option value=215>Almeirim</option>
    <option value=216>Alpiarça</option>
    <option value=217>Benavente</option>
</optgroup>
<optgroup label="Setúbal">
    <option value=218>Moita</option>
    <option value=219>Montijo</option>
    <option value=220>Palmela</option>
    <option value=221>Santiago do Cacém</option>
    <option value=222>Seixal</option>
    <option value=223>Sesimbra</option>
    <option value=224>Setúbal</option>
    <option value=225>Sines</option>
    <option value=226>Alcácer do Sal</option>
    <option value=227>Alcochete</option>
    <option value=228>Almada</option>
    <option value=229>Barreiro</option>
    <option value=230>Grândola</option>
</optgroup>
<optgroup label="Viana do Castelo">
    <option value=231>Ponte da Barca</option>
    <option value=232>Ponte de Lima</option>
    <option value=233>Valença</option>
    <option value=234>Viana do Castelo</option>
    <option value=235>Vila Nova de Cerveira</option>
    <option value=236>Arcos de Valdevez</option>
    <option value=237>Caminha</option>
    <option value=238>Melgaço</option>
    <option value=239>Monção</option>
    <option value=240>Paredes de Coura</option>
</optgroup>
<optgroup label="Vila Real">
    <option value=241>Mondim de Basto</option>
    <option value=242>Montalegre</option>
    <option value=243>Murça</option>
    <option value=244>Peso da Régua</option>
    <option value=245>Ribeira de Pena</option>
    <option value=246>Sabrosa</option>
    <option value=247>Santa Marta de Penaguião</option>
    <option value=248>Valpaços</option>
    <option value=249>Vila Pouca de Aguiar</option>
    <option value=250>Vila Real</option>
    <option value=251>Alijó</option>
    <option value=252>Boticas</option>
    <option value=253>Chaves</option>
    <option value=254>Mesão Frio</option>
</optgroup>
<optgroup label="Viseu">
    <option value=255>Lamego</option>
    <option value=256>Mangualde</option>
    <option value=257>Moimenta da Beira</option>
    <option value=258>Mortágua</option>
    <option value=259>Nelas</option>
    <option value=260>Oliveira de Frades</option>
    <option value=261>Penalva do Castelo</option>
    <option value=262>Penedono</option>
    <option value=263>Resende</option>
    <option value=264>Santa Comba Dão</option>
    <option value=265>São João da Pesqueira</option>
    <option value=266>São Pedro do Sul</option>
    <option value=267>Sátão</option>
    <option value=268>Sernancelhe</option>
    <option value=269>Tabuaço</option>
    <option value=270>Tarouca</option>
    <option value=271>Tondela</option>
    <option value=272>Vila Nova de Paiva</option>
    <option value=273>Viseu</option>
    <option value=274>Vouzela</option>
    <option value=275>Armamar</option>
    <option value=276>Carregal do Sal</option>
    <option value=277>Castro Daire</option>
    <option value=278>Cinfães</option>
</optgroup>
<optgroup label="Ilha da Madeira">
    <option value=279>Ponta do Sol</option>
    <option value=280>Porto Moniz</option>
    <option value=281>Ribeira Brava</option>
    <option value=282>Santa Cruz</option>
    <option value=283>Santana</option>
    <option value=284>São Vicente</option>
    <option value=285>Calheta (Madeira)</option>
    <option value=286>Câmara de Lobos</option>
    <option value=287>Funchal</option>
    <option value=288>Machico</option>
</optgroup>
<optgroup label="Ilha de Porto Santo">
    <option value=289>Porto Santo</option>
</optgroup>
<optgroup label="Ilha de Santa Maria">
    <option value=290>Vila do Porto</option>
</optgroup>
<optgroup label="Ilha de São Miguel">
    <option value=291>Ribeira Grande</option>
    <option value=292>Vila Franca do Campo</option>
    <option value=293>Lagoa (São Miguel)</option>
    <option value=294>Nordeste</option>
    <option value=295>Ponta Delgada</option>
    <option value=296>Povoação</option>
</optgroup>
<optgroup label="Ilha Terceira">
    <option value=297>Angra do Heroísmo</option>
    <option value=298>Praia da Vitória</option>
</optgroup>
<optgroup label="Ilha da Graciosa">
    <option value=299>Santa Cruz da Graciosa</option>
</optgroup>
<optgroup label="Ilha de São Jorge">
    <option value=300>Calheta (São Jorge)</option>
    <option value=301>Velas</option>
</optgroup>
<optgroup label="Ilha do Pico">
    <option value=302>Lajes do Pico</option>
    <option value=303>Madalena</option>
    <option value=304>São Roque do Pico</option>
</optgroup>
<optgroup label="Ilha do Faial">
    <option value=305>Horta</option>
</optgroup>
<optgroup label="Ilha das Flores">
    <option value=306>Lajes das Flores</option>
    <option value=307>Santa Cruz das Flores</option>
</optgroup>
<optgroup label="Ilha do Corvo">
    <option value=308>Corvo</option>
</optgroup>



