<option value="1">Aveiro</option>
<option value="2">Beja</option>
<option value="3">Braga</option>
<option value="4">Bragança</option>
<option value="5">Castelo Branco</option>
<option value="6">Coimbra</option>
<option value="7">Évora</option>
<option value="8">Faro</option>
<option value="9">Guarda</option>
<option value="10">Leiria</option>
<option value="11">Lisboa</option>
<option value="12">Portalegre</option>
<option value="13">Porto</option>
<option value="14">Santarém</option>
<option value="15">Setúbal</option>
<option value="16">Viana do Castelo</option>
<option value="17">Vila Real</option>
<option value="18">Viseu</option>
<option value="31">Ilha da Madeira</option>
<option value="32">Ilha de Porto Santo</option>
<option value="41">Ilha de Santa Maria</option>
<option value="42">Ilha de São Miguel</option>
<option value="43">Ilha Terceira</option>
<option value="44">Ilha da Graciosa</option>
<option value="45">Ilha de São Jorge</option>
<option value="46">Ilha do Pico</option>
<option value="47">Ilha do Faial</option>
<option value="48">Ilha das Flores</option>
<option value="49">Ilha do Corvo</option>